services:
  nginxproxymanager:
    container_name: nginxproxymanager
    image: jc21/nginx-proxy-manager:latest
    restart: always
    ports:
      - 80:80
      - 443:443
      - 81:81
    volumes:
      - /mnt/data/nginxproxymanager/data:/data
      - /mnt/data/nginxproxymanager/certs:/etc/letsencrypt
    networks:
      - local

networks:
  local:
