services:
  nginxproxymanager:
    container_name: nginxproxymanager
    image: jc21/nginx-proxy-manager:latest
    restart: always
    user: "${UID}:${GID}"
    ports:
      - "80:80"
      - "443:443"
      - "81:81"
    volumes:
      - data:/data
      - certs:/etc/letsencrypt
    networks:
      - local

volumes:
  data:
  certs:

networks:
  local:
