services:
  duckdns:
    container_name: duckdns
    image: lscr.io/linuxserver/duckdns
    restart: always
    user: "${UID}:${GID}"
    environment:
      - TZ=${TZ} # cat /etc/timezone
      - SUBDOMAINS=${SUBDOMAINS}
      - TOKEN=${TOKEN}
      - LOG_FILE=false
    volumes:
      - config:/config
    networks:
      - local

volumes:
  config:

networks:
  local:
