services:
  duckdns:
    container_name: duckdns
    image: lscr.io/linuxserver/duckdns
    restart: always
    environment:
      - TZ=${TZ} # cat /etc/timezone
      - SUBDOMAINS=${SUBDOMAINS}
      - TOKEN=${TOKEN}
      - LOG_FILE=false
    volumes:
      - /mnt/data/duckdns/config:/config
    networks:
      - local

networks:
  local:
