services:
  homeassistant:
    container_name: homeassistant
    image: ghcr.io/home-assistant/home-assistant:stable
    restart: always
    privileged: true
    environment:
      - TZ=${TZ} # cat /etc/timezone
    devices:
      - ${DEVICE}:/dev/ttyUSB0 # ls -l /dev/serial/by-id/
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/data/homeassistant/config:/config
    networks:
      - local

volumes:
  config:

networks:
  local:
