services:
  pihole:
    container_name: pihole
    image: pihole/pihole
    restart: always
    user: "${UID}:${GID}"
    environment:
      - TZ=${TZ} # cat /etc/timezone
      - WEBPASSWORD=${WEBPASSWORD}
    volumes:
      - /mnt/data/pihole/config:/etc/pihole
      - /mnt/data/pihole/dnsmasq:/etc/dnsmasq.d
    ports:
      - "53:53/tcp"
    networks:
      - local

networks:
  local:
