services:
  pihole:
    container_name: pihole
    image: pihole/pihole
    restart: always
    environment:
      - TZ=$(cat /etc/timezone)
      - WEBPASSWORD=changeme
    volumes:
      - /mnt/data/pihole/config:/etc/pihole
      - /mnt/data/pihole/dnsmasq:/etc/dnsmasq.d
    ports:
      - 53:53
    networks:
      - local

networks:
  local:
