version: "3.8"

services:
  grafana:
    container_name: grafana
    image: grafana/grafana
    restart: always
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=changeme
      - GF_SECURITY_ALLOW_EMBEDDING=true
      - GF_INSTALL_PLUGINS=
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - local
  influxdb:
    container_name: influxdb
    image: influxdb:1.8-alpine
    restart: always
    environment:
      - INFLUXDB_DB=influxdb
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
    volumes:
      - influxdb_data:/var/lib/influxdb
    networks:
      - local
  telegraf:
    container_name: telegraf
    image: telegraf
    restart: always
    environment:
      - HOST_ETC=/hostfs/etc
      - HOST_PROC=/hostfs/proc
      - HOST_SYS=/hostfs/sys
      - HOST_VAR=/hostfs/var
      - HOST_RUN=/hostfs/run
      - HOST_MOUNT_PREFIX=/hostfs
    volumes:
      - /:/hostfs:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - telegraf_config:/etc/telegraf
      - ./telegraf.conf:/etc/telegraf/telegraf.conf
    networks:
      - local

volumes:
  grafana_data:
  influxdb_data:
  telegraf_config:

networks:
  local:
