services:
  nodered:
    container_name: nodered
    image: nodered/node-red:latest
    restart: always
    environment:
      - TZ=$(cat /etc/timezone)
    volumes:
      - /mnt/data/nodered/data:/data
    networks:
      - local

networks:
  local:
