version: "3.8"

services:
  nodered:
    container_name: nodered
    image: nodered/node-red:latest
    restart: always
    environment:
      - TZ=$TZ
    volumes:
      - data:/data
    networks:
      - local

volumes:
  data:

networks:
  local:
