services:
  nodered:
    container_name: nodered
    image: nodered/node-red:latest
    restart: always
    user: "${UID}:${GID}"
    environment:
      - TZ=${TZ} # cat /etc/timezone
    volumes:
      - data:/data
    networks:
      - local

volumes:
  data:

networks:
  local:
