services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /mnt/data/portainer/data:/data
    networks:
      - local

networks:
  local:
