services:
  dashy:
    container_name: dashy
    image: lissy93/dashy
    restart: always
    user: "${UID}:${GID}"
    volumes:
      - config:/app/public
    networks:
      - local

volumes:
  config:

networks:
  local:
