services:
  wireguard:
    container_name: wireguard
    image: ghcr.io/wg-easy/wg-easy
    restart: always
    environment:
      - WG_HOST=${WG_HOST}
      - PASSWORD_HASH=${PASSWORD_HASH} # docker run --rm -it ghcr.io/wg-easy/wg-easy wgpw 'changeme'
      - ENABLE_PROMETHEUS_METRICS=true
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    ports:
      - 51820:51820/udp
    volumes:
      - /mnt/data/wireguard/data:/etc/wireguard
    networks:
      - local

networks:
  local:
